[package]
name = "heater-control"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.7.1"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros", "fs", "io-util"] }
futures = "0.3.31"

anyhow = "1.0.98"
